apiVersion: apps/v1
kind: Deployment
metadata:
  name: czhellodocker
spec:
  selector:
    matchLabels:
      app: czhellodocker
  template:
    metadata:
      labels:
        app: czhellodocker
    spec:
      containers:
      - name: hello-docker-container
        image: czcontainerreg.azurecr.io/czhellodocker:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
