apiVersion : apps/v1
kind: Deployment
metadata:
  name: czhellodocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: czhellodocker 
    spec:
      containers:
        - name: czhellodocker 
          image: czcontainerreg.azurecr.io/czhellodocker
          ports:
          - containerPort: 80
