apiVersion: apps/v1
kind: Deployment
metadata:
  name: czhellodocker-deployment
spec:
  selector:
    matchLabels:
      app: czhellodocker-pod
  template:
    metadata:
      labels:
        app: czhellodocker-pod
    spec:
      containers:
      - name: hello-docker-container
        image: czacrtest.azurecr.io/czhellodocker:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80



