apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-docker-deployment
spec:
  selector:
    matchLabels:
      app: hello-docker-pod
  template:
    metadata:
      labels:
        app: hello-docker-pod
    spec:
      containers:
      - name: hello-docker-container
        image: czcontainerreg.azurecr.io/hellodocker:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
